"""
SQLRenderer: generate DDL scripts from the AccessCatalog.

Produces:
  - CREATE TABLE statements for all non-system, non-linked tables
  - ALTER TABLE ADD CONSTRAINT for foreign keys (from Relations)
  - CREATE INDEX statements
  - Translated query views (optional)

Dialect support: postgres, sqlite, mssql
"""

from __future__ import annotations

import re
from pathlib import Path

from access_dissect.catalog.models import AccessCatalog, FieldDef, FieldType, RelationDef
from access_dissect.translate.sql_rewriter import translate_sql
from access_dissect.translate.type_map import field_type_to_sql

_BINARY_FIELDS = {FieldType.OLE_OBJECT, FieldType.ATTACHMENT}


def _quote(name: str, dialect: str) -> str:
    """Quote an identifier for the target dialect."""
    if dialect == "mssql":
        return f"[{name}]"
    return f'"{name}"'


def _field_to_ddl(field: FieldDef, dialect: str) -> str:
    """Generate a column definition line."""
    sql_type = field_type_to_sql(field.field_type, dialect, field.size)
    col_name = _quote(field.name, dialect)

    parts = [f"  {col_name} {sql_type}"]

    if field.field_type in _BINARY_FIELDS:
        parts = [f"  {col_name} {sql_type}  -- WARNING: binary field, define storage strategy"]
        return parts[0]

    if field.auto_number:
        if dialect == "postgres":
            parts = [f"  {col_name} SERIAL"]
        elif dialect == "mssql":
            parts = [f"  {col_name} INT IDENTITY(1,1)"]
        # SQLite: INTEGER PRIMARY KEY is auto-increment

    if field.required:
        parts.append("NOT NULL")

    if field.default_value:
        dv = field.default_value
        # Access uses double-quotes for string defaults; convert to single-quote
        dv = dv.replace('"', "'")
        # Remove leading = sign
        dv = dv.lstrip("=").strip()
        parts.append(f"DEFAULT {dv}")

    return " ".join(parts)


def generate_ddl(
    catalog: AccessCatalog,
    dialect: str = "postgres",
    include_queries: bool = False,
    include_indexes: bool = True,
) -> str:
    """
    Generate a DDL script from the catalog.

    Returns the full DDL as a string.
    """
    lines: list[str] = []
    lines.append(f"-- DDL generated by access-dissect")
    lines.append(f"-- Source: {catalog.properties.file_path}")
    lines.append(f"-- Dialect: {dialect}")
    lines.append(f"-- Tables: {len(catalog.tables)}")
    lines.append("")

    # Tables
    for table in catalog.tables:
        if table.is_system_table or table.is_hidden:
            continue
        if table.is_linked:
            lines.append(f"-- Linked table: {table.name}")
            if table.linked_source:
                lines.append(f"-- Source: {table.linked_source.connect_string[:60]}")
            lines.append(f"-- CREATE TABLE for linked table not generated (external source)")
            lines.append("")
            continue

        tbl_name = _quote(table.name, dialect)
        lines.append(f"CREATE TABLE {tbl_name} (")

        col_lines: list[str] = []
        pk_fields: list[str] = []

        for field in table.fields:
            col_lines.append(_field_to_ddl(field, dialect))
            if field.is_primary_key:
                pk_fields.append(_quote(field.name, dialect))

        if pk_fields:
            col_lines.append(f"  PRIMARY KEY ({', '.join(pk_fields)})")

        lines.append(",\n".join(col_lines))
        lines.append(");")
        lines.append("")

    # Indexes (non-primary, non-foreign)
    if include_indexes:
        lines.append("-- Indexes")
        for table in catalog.tables:
            if table.is_system_table or table.is_linked:
                continue
            tbl_name = _quote(table.name, dialect)
            for idx in table.indexes:
                if idx.primary or idx.foreign:
                    continue
                safe_idx_name = re.sub(r"[^a-zA-Z0-9_]", "_", f"idx_{table.name}_{idx.name}")
                idx_name = _quote(safe_idx_name, dialect)
                unique_kw = "UNIQUE " if idx.unique else ""
                col_list = ", ".join(_quote(f.field_name, dialect) for f in idx.fields)
                lines.append(
                    f"CREATE {unique_kw}INDEX {idx_name} ON {tbl_name} ({col_list});"
                )
        lines.append("")

    # Foreign Keys (from Relations with enforce_integrity=True)
    enforced_rels = [r for r in catalog.relations if r.enforce_integrity]
    if enforced_rels:
        lines.append("-- Foreign Key Constraints")
        for i, rel in enumerate(enforced_rels):
            parent = _quote(rel.parent_table, dialect)
            child = _quote(rel.child_table, dialect)
            fk_name = _quote(
                re.sub(r"[^a-zA-Z0-9_]", "_", f"fk_{rel.child_table}_{rel.name}"),
                dialect,
            )
            child_cols = ", ".join(_quote(f.child_field, dialect) for f in rel.fields)
            parent_cols = ", ".join(_quote(f.parent_field, dialect) for f in rel.fields)

            cascade = ""
            if rel.cascade_update:
                cascade += " ON UPDATE CASCADE"
            if rel.cascade_delete:
                cascade += " ON DELETE CASCADE"

            lines.append(
                f"ALTER TABLE {child} ADD CONSTRAINT {fk_name}\n"
                f"  FOREIGN KEY ({child_cols}) REFERENCES {parent} ({parent_cols}){cascade};"
            )
        lines.append("")

    # Translated queries (as VIEWs)
    if include_queries:
        lines.append("-- Views (translated from Access queries)")
        for query in catalog.queries:
            if query.query_type.value not in ("select", "union"):
                continue
            view_name = _quote(
                re.sub(r"[^a-zA-Z0-9_]", "_", query.name),
                dialect,
            )
            translated_sql, _warns = translate_sql(query.sql_text, dialect, query.name)
            lines.append(f"-- Query: {query.name}")
            lines.append(f"CREATE OR REPLACE VIEW {view_name} AS")
            lines.append(translated_sql + ";")
            lines.append("")

    return "\n".join(lines)


def save_ddl(
    catalog: AccessCatalog,
    output_path: Path,
    dialect: str = "postgres",
    include_queries: bool = False,
) -> None:
    """Write DDL to a file."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ddl = generate_ddl(catalog, dialect, include_queries=include_queries)
    output_path.write_text(ddl, encoding="utf-8")
